export const METADATA = {
    title: "Portfolio | Semir Hamid",
    description:
        "Semir Hamid is a Full Stack and mobile Developer from Ethiopia, interested in crafting beautiful and functional applications. Semir is pursuing his undergraduate from Addis Ababa University, Ethiopia.",
    siteUrl: "https://semirhamid.me/",
    twitterHandle: "@SemirHamid1756",
};

export const MENULINKS = [
    {
        name: "Home",
        ref: "home",
    },
    {
        name: "Skills",
        ref: "skills",
    },
    {
        name: "Projects",
        ref: "projects",
    },
    {
        name: "Work",
        ref: "work",
    },
    {
        name: "Contact",
        ref: "contact",
    },
];

export const TYPED_STRINGS = [
    "Full Stack and mobile developer",
    "Innovative solutions for the all platforms",
    "Creating Modern & Aesthetic Apps",
];

export const SOCIAL_LINKS = [
    {
        name: "mail",
        url: "mailto: semhamirid@gmail.com",
    },
    {
        name: "linkedin",
        url: "https://www.linkedin.com/in/semir-hamid-1b9b8b1b7/",
    },
    {
        name: "github",
        url: "https://github.com/semirhamid",
    },
    {
        name: "instagram",
        url: "https://www.instagram.com/the_slave_of_almighty/",
    },
    {
        name: "twitter",
        url: "https://twitter.com/SemirHamid1756",
    },
];

export const SKILLS = {
    languagesAndTools: [
        "html",
        "css",
        "javascript",
        "typescript",
        "sass",
        "csharp",
        "java",
        "python",
        // "figma"
    ],
    librariesAndFrameworks: [
        "react",
        "redux",
        "asp_net_core",
        "tailwindcss",
        "styledcomponents",
        "flutter",
        "nodejs",
        "express",
    ],
    databases: ["mysql", "mongodb", "postgressql"],
    other: ["wordpress", "git", "sanity-io"],
};

export const PROJECTS = [
    {
        name: "Recognise Design ",
        image: "/projects/recognise.png",
        blurImage: "/projects/blur/recognise-blur.png",
        description: "Company portfolio and showcase",
        gradient:["#4687F1", "#147AED"],
        url: "https://recognisedesign.com/",
        tech: [ "wordpress","typescript","react"],
    },
    {
        name: "ECC Admin panel",
        image: "/projects/ecc-admin.png",
        blurImage: "/projects/blur/ecc-admin-blur.png",
        description: "ECC Admin Panel",
        gradient:["#D664DA", "#D818DE"],
        url: "https://columbusassicurazioni.it/",
        tech: [ "sass","typescript","react", "nextjs"],
    },
    {
        name: "Columbus Italy",
        image: "/projects/columbus.png",
        blurImage: "/projects/blur/columbus-blur.png",
        description: "Umbraco + Asp net core (On Progress)",
        gradient: ["#F0B369", "#EA8F1F"],
        url: "https://columbusassicurazioni.it/",
        tech: [ "sass","typescript","asp_net_core"],
    },
    {
        name: "Berkeley Square Medical",
        image: "/projects/berkeley.png",
        blurImage: "/projects/blur/berkeley-blur.png",
        description: "Wordpress + Custom Theme",
        gradient: ["#522356", "#939504"],
        url: "https://electriccarchargersuk.co.uk/",
        tech: ["css", "wordpress","php"],
    },
    {
        name: "ECC",
        image: "/projects/ecc.png",
        blurImage: "/projects/blur/ecc-blur.png",
        description: "Wordpress + Custom Theme",
        gradient: ["#81EEFF", "#0B9DF8"],
        url: "https://electriccarchargersuk.co.uk/",
        tech: ["css", "wordpress","php"],
    },
    
    {
        name: "Virtue Gymnastic CO",
        image: "/projects/virtue.png",
        blurImage: "/projects/blur/virtue-blur.png",
        description: "Next js + Strapi",
        gradient: ["#81EEFF", "#0B9DF8"],
        url: "https://virtue-gym-frontend-production.up.railway.app/",
        tech: ["react", "nextjs", "tailwindcss"],
    },
    {
        name: "Place to be Ethiopia Mobile App",
        image: "/projects/p2bmobile.png",
        blurImage: "/projects/blur/p2bmobileblur.png",
        description: "React + css",
        gradient: ["#0EF32D", "#0BF83E"],
        url: "https://play.google.com/store/apps/details?id=com.afromina.placetobe",
        tech: ["react", "mui", "mapbox"],
    },
    {
        name: "Place to be Ethiopia Web",
        image: "/projects/p2bweb.png",
        blurImage: "/projects/blur/p2bwebblur.png",
        description: "React + css",
        gradient: ["#4687F1", "#147AED"],
        url: "https://placetobeethiopia.com/",
        tech: ["react", "nextjs", "tailwindcss", "mapbox"],
    },
    {
        name: "Bisrate Gebriel Internation School Management",
        image: "/projects/bgis.png",
        blurImage: "/projects/blur/bgis_blur.webp",
        description: "React + css",
        gradient: ["#F14658", "#DC2537"],
        url: "http://138.68.155.204/",
        tech: ["react", "nextjs", "tailwindcss", "mapbox"],
    },
    {
        name: "Bisrate Gebriel Internation Mobile App",
        image: "/projects/bgis_mobile.jpg",
        blurImage: "/projects/blur/bgis_mobile_blur.webp",
        description: "React Native + css",
        gradient: ["#46F1AA", "#00CB3D"],
        url: "http://138.68.155.204/",
        tech: ["react", "nextjs", "tailwindcss", "mapbox"],
    },
    {
        name: "Merkato Market Ecommerce",
        image: "/projects/merkato_market.jpg",
        blurImage: "/projects/blur/merkato_market.webp",
        description: "React + css + sass",
        gradient: ["#46C0F1", "#254ADC"],
        url: "https://github.com/semirhamid/Merkato-Market",
        tech: ["react", "nextjs", "tailwindcss", "mapbox"],
    },
    {
        name: "Kebele Management System",
        image: "/projects/kebele.png",
        blurImage: "/projects/kebele_blur.jpg",
        description: "React + css + sass + Asp Net Core",
        gradient: ["#46F1AA", "#254ADC"],
        url: "https://github.com/semirhamid",
        tech: ["react", "nextjs", "tailwindcss", "mapbox"],
    },
    {
        name: "Engineering Calculator",
        image: "/projects/calculator.jpg",
        blurImage: "/projects/calculator.jpg",
        description: "flutter",
        gradient: ["#F0B369", "#EA8F1F"],
        url: "https://github.com/semirhamid/PostgresDbBackupandRestore",
        tech: ["flutter"],
    },
    {
        name: "Electricity Billing System",
        image: "/projects/electricity_billing.png",
        blurImage: "/projects/electricity_billing.png",
        description: "React + css + sass + Asp Net Core",
        gradient: ["#522356", "#254ADC"],
        url: "https://github.com/semirhamid",
        tech: ["react", "nextjs", "tailwindcss", "mapbox"],
    },
    {
        name: "CSharp to MIPS Compiler",
        image: "/projects/compiler.png",
        blurImage: "/projects/blur/complier.webp",
        description: "React + css + sass",
        gradient: ["#D664DA", "#D818DE"],
        url: "https://github.com/semirhamid/Csharp-to-Assembly",
        tech: ["react", "nextjs", "tailwindcss", "mapbox"],
    },
    {
        name: "Fitness Tracking App",
        image: "/projects/fitness.jpg",
        blurImage: "/projects/blur/fitness.webp",
        description: "Flutter + BLoC",
        gradient: ["#522356", "#939504"],
        url: "https://github.com/semirhamid/Fitness-Tracking",
        tech: ["react", "nextjs", "tailwindcss", "mapbox"],
    },
    {
        name: "Postgres DB Backup Packages",
        image: "/projects/postgres.jfif",
        blurImage: "/projects/blur/postgres.webp",
        description: "CSharp + Asp Net Core",
        gradient: ["#F0B369", "#EA8F1F"],
        url: "https://github.com/semirhamid/PostgresDbBackupandRestore",
        tech: ["react", "nextjs", "tailwindcss", "mapbox"],
    },
    {
        name: "Cinema Movies",
        image: "/projects/movie.jpg",
        blurImage: "/projects/blur/movie.webp",
        description: "CSharp + Asp Net Core + React",
        gradient: ["#F14658", "#DC2537"],
        url: "https://github.com/semirhamid/Cinema-Movie",
        tech: ["react", "nextjs", "tailwindcss", "mapbox"],
    },
];

export const WORK = [
    {
    company: "AfroMina Digitals",
    title: "Front End and Mobile Developer",
    location: "Addis Ababa, Ethiopia",
    range: "May 2023 - Present",
    responsibilities: [
        "Collaborated with the AfroMina Digitals team to develop the 'Place to Be Ethiopia' project, a web and mobile application for event management and ticket sales.",
        "Developed and maintained the frontend of the application using React and Material-UI (MUI) to create a visually appealing and user-friendly interface.",
        "Utilized React Native to build the mobile version of the application, enabling users to access event details and purchase tickets from their smartphones.",
        "Worked closely with the backend team to integrate frontend components with the necessary APIs to ensure seamless data flow and functionality.",
        "Implemented responsive design principles to ensure the application's compatibility across various devices and screen sizes.",
        "Contributed to the implementation of user authentication and authorization features to safeguard user data and manage access to certain functionalities.",
        "Collaborated with UX/UI designers to transform wireframes and mockups into fully functional and aesthetically pleasing user interfaces.",
        "Optimized the application's performance to provide a smooth and responsive user experience, minimizing load times and enhancing overall speed.",
        "Participated in regular testing and debugging to identify and address any frontend-related issues or bugs.",
        "Collaborated with the QA team to conduct usability testing and gather user feedback for further improvements.",
        "Stayed up-to-date with the latest frontend and mobile development trends and best practices to continuously enhance the application's quality and user experience.",
    ],
    url: "https://afromina-digitals.com/",
    },
    {
        company: "Bisrate Gebriel International School",
        title: "Full Stack and Mobile Developer",
        location: "Addis Ababa, Ethiopia",
        range: "January 2022 - Present",
        responsibilities: [
            "Collaborated with a personal custom group of teachers to develop a comprehensive school management app for Bisrate Gebriel International School.",
            "Developed and maintained web applications using technologies like React, NestJS, and ASP.NET Core to facilitate various school activities.",
            "Designed and developed mobile applications using Flutter and React Native, allowing easy access to school management features on the go.",
            "Built and maintained APIs using NestJS and ASP.NET Core, ensuring smooth communication between the frontend and backend systems.",
            "Ensured the codebase was clean, efficient, and well-documented for better maintainability and future enhancements.",
            "Worked closely with cross-functional teams to understand and implement software solutions that catered to specific school management needs.",
            "Identified and resolved software issues promptly to maintain a reliable and seamless user experience.",
            "Participated in code reviews and provided constructive feedback to fellow developers, fostering a collaborative and learning-oriented environment.",
            "Optimized web and mobile applications for better performance, scalability, and security, ensuring an optimal user experience.",
            "Conducted thorough testing of software releases to deliver high-quality, bug-free applications.",
            "Contributed to the continuous improvement of the school management app, incorporating user feedback and innovative features.",
        ],
        url: "School's internal app, not publicly available",
    },
    {
        company: "DEP",
        title: "Full Stack and Mobile Developer",
        location: "Addis Ababa, Ethiopia",
        range: "January 2022",
        responsibilities: [
            "Develop and maintain web applications using React, NestJS, and ASP.NET Core",
            "Design and develop mobile applications using Flutter and React Native",
            "Build and maintain APIs using NestJS and ASP.NET Core",
            "Write clean, efficient, and well-documented code",
            "Collaborate with cross-functional teams to develop software solutions that meet business requirements",
            "Troubleshoot and debug software issues in a timely manner",
            "Participate in code reviews and provide feedback to other developers",
            "Optimize web and mobile applications for performance, scalability, and security",
            "Test and deploy software releases, ensuring high quality and reliability",
        ],
        url: "https://dep.com/",
    },
    {
        company: "UCD Ethiopia",
        title: "Full Stack Developer",
        location: "Addis Ababa, Ethiopia",
        range: "September 2020 - January 2022",
        responsibilities: [
            "Develop and maintain the NGO's website using appropriate technologies such as HTML, CSS, JavaScript, and WordPress.",
            "Design and implement internal communication strategies using various tools such as email, Slack, and social media platforms.",
            "Create and manage website content, including text, images, and multimedia content.",
            "Ensure that the NGO's website is responsive, user-friendly, and accessible to all users, including those with disabilities.",
            "Monitor website traffic and engagement using tools such as Google Analytics and provide regular reports to stakeholders.",
            "Troubleshoot and resolve website issues, including server errors, broken links, and user complaints.",
            "Collaborate with cross-functional teams, including content creators, graphic designers, and web developers to ensure that the website meets the needs of the NGO.",
        ],
        url: "https://ucdethiopia.com/",
    },
    {
        company: "CODIIZ",
        title: "Front End Developer",
        location: "Addis Ababa, Ethiopia",
        range: "September 2021 - August 2021",
        responsibilities: [
            "Develop and maintain front-end applications using React, Redux, and related technologies.",
            "Design and implement user interfaces that are responsive, intuitive, and visually appealing.",
            "Collaborate with UI/UX designers to ensure that the front-end design is consistent with the overall design vision.",
            "Write clean, efficient, and well-documented code that is easy to maintain and scale.",
            "Optimize front-end applications for performance, scalability, and security.",
            "Test and debug front-end code to ensure that it meets functional and non-functional requirements.",
        ],
        url: "https://codiiz.com/",
    },
];

export const GTAG = "G-5HCTL2TJ5W";
